// Package media stores uploaded files (attachments, avatars) and checks them: the type is detected from the
// content, images are re-encoded, voice messages measured, and nothing is ever served in a way a browser
// would run. Bytes live in object storage (S3-compatible) or, for development, on disk; metadata and access
// rules are in PostgreSQL (attachments, attachment_links).
package media

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

// ErrNotFound is returned for an object that does not exist.
var ErrNotFound = errors.New("media: object not found")

// Object is a stored object being read.
type Object struct {
	Body io.ReadCloser
	Size int64
}

// Storage holds the bytes. Keys are generated by the server (attachments/{uuid}), never derived from user input.
type Storage interface {
	Put(ctx context.Context, key string, r io.Reader, size int64, contentType string) error
	Get(ctx context.Context, key string) (Object, error)
	Delete(ctx context.Context, key string) error
	// SignedURL returns a short-lived URL the client can download the object from directly, with the given
	// download headers, or "" when the backend cannot sign (the API then streams the object itself).
	SignedURL(ctx context.Context, key string, ttl time.Duration, contentType, disposition string) (string, error)
}

// validKey allows only the key shapes the server creates.
func validKey(key string) bool {
	if key == "" || len(key) > 200 || strings.Contains(key, "..") || strings.HasPrefix(key, "/") {
		return false
	}
	for _, r := range key {
		lower, digit := r >= 'a' && r <= 'z', r >= '0' && r <= '9'
		if !lower && !digit && r != '-' && r != '/' && r != '.' && r != '_' {
			return false
		}
	}
	return true
}

// ---------------------------------------------------------------- disk

// Disk stores objects under a directory (development and tests).
type Disk struct{ root string }

// NewDisk returns a disk store, creating the directory.
func NewDisk(root string) (*Disk, error) {
	if err := os.MkdirAll(root, 0o750); err != nil {
		return nil, fmt.Errorf("media: %w", err)
	}
	abs, err := filepath.Abs(root)
	if err != nil {
		return nil, fmt.Errorf("media: %w", err)
	}
	return &Disk{root: abs}, nil
}

func (d *Disk) path(key string) (string, error) {
	if !validKey(key) {
		return "", errors.New("media: invalid key")
	}
	return filepath.Join(d.root, filepath.FromSlash(key)), nil
}

// Put implements Storage. The file appears under its name only when complete.
func (d *Disk) Put(_ context.Context, key string, r io.Reader, _ int64, _ string) error {
	p, err := d.path(key)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(p), 0o750); err != nil {
		return fmt.Errorf("media: %w", err)
	}
	tmp, err := os.CreateTemp(filepath.Dir(p), ".upload-*")
	if err != nil {
		return fmt.Errorf("media: %w", err)
	}
	defer func() { _ = os.Remove(tmp.Name()) }()
	if _, err := io.Copy(tmp, r); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("media: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("media: %w", err)
	}
	if err := os.Rename(tmp.Name(), p); err != nil {
		return fmt.Errorf("media: %w", err)
	}
	return nil
}

// Get implements Storage.
func (d *Disk) Get(_ context.Context, key string) (Object, error) {
	p, err := d.path(key)
	if err != nil {
		return Object{}, err
	}
	f, err := os.Open(p) //nolint:gosec // the key was validated and is joined to the root
	if errors.Is(err, os.ErrNotExist) {
		return Object{}, ErrNotFound
	}
	if err != nil {
		return Object{}, fmt.Errorf("media: %w", err)
	}
	st, err := f.Stat()
	if err != nil {
		_ = f.Close()
		return Object{}, fmt.Errorf("media: %w", err)
	}
	return Object{Body: f, Size: st.Size()}, nil
}

// Delete implements Storage; a missing object is not an error.
func (d *Disk) Delete(_ context.Context, key string) error {
	p, err := d.path(key)
	if err != nil {
		return err
	}
	if err := os.Remove(p); err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("media: %w", err)
	}
	return nil
}

// SignedURL implements Storage: a disk cannot sign, the API streams.
func (d *Disk) SignedURL(context.Context, string, time.Duration, string, string) (string, error) {
	return "", nil
}

// ---------------------------------------------------------------- S3

// S3Options configures the S3-compatible store.
type S3Options struct {
	// Endpoint is the URL of the service, e.g. https://s3.eu-central-1.amazonaws.com or http://object-storage:9000.
	Endpoint  string
	AccessKey string
	SecretKey string
	Bucket    string
	Region    string
	// PublicEndpoint, when set, is used for signed URLs instead of Endpoint (the address clients reach).
	PublicEndpoint string
}

// S3 stores objects in an S3-compatible bucket.
type S3 struct {
	client *minio.Client
	signer *minio.Client
	bucket string
}

func newMinio(endpoint string, o S3Options) (*minio.Client, error) {
	u, err := url.Parse(endpoint)
	if err != nil || u.Host == "" || (u.Scheme != "http" && u.Scheme != "https") {
		return nil, errors.New("media: S3 endpoint must be an http(s) URL")
	}
	return minio.New(u.Host, &minio.Options{
		Creds:  credentials.NewStaticV4(o.AccessKey, o.SecretKey, ""),
		Secure: u.Scheme == "https",
		Region: o.Region,
	})
}

// NewS3 returns an S3 store; it does not connect.
func NewS3(o S3Options) (*S3, error) {
	if o.Bucket == "" {
		return nil, errors.New("media: S3 bucket is required")
	}
	c, err := newMinio(o.Endpoint, o)
	if err != nil {
		return nil, err
	}
	signer := c
	if o.PublicEndpoint != "" {
		if signer, err = newMinio(o.PublicEndpoint, o); err != nil {
			return nil, err
		}
	}
	return &S3{client: c, signer: signer, bucket: o.Bucket}, nil
}

// Put implements Storage.
func (s *S3) Put(ctx context.Context, key string, r io.Reader, size int64, contentType string) error {
	if !validKey(key) {
		return errors.New("media: invalid key")
	}
	_, err := s.client.PutObject(ctx, s.bucket, key, r, size, minio.PutObjectOptions{ContentType: contentType})
	if err != nil {
		return fmt.Errorf("media: %w", err)
	}
	return nil
}

// Get implements Storage.
func (s *S3) Get(ctx context.Context, key string) (Object, error) {
	if !validKey(key) {
		return Object{}, errors.New("media: invalid key")
	}
	obj, err := s.client.GetObject(ctx, s.bucket, key, minio.GetObjectOptions{})
	if err != nil {
		return Object{}, fmt.Errorf("media: %w", err)
	}
	st, err := obj.Stat()
	if err != nil {
		_ = obj.Close()
		if minio.ToErrorResponse(err).Code == "NoSuchKey" {
			return Object{}, ErrNotFound
		}
		return Object{}, fmt.Errorf("media: %w", err)
	}
	return Object{Body: obj, Size: st.Size}, nil
}

// Delete implements Storage; a missing object is not an error.
func (s *S3) Delete(ctx context.Context, key string) error {
	if !validKey(key) {
		return errors.New("media: invalid key")
	}
	if err := s.client.RemoveObject(ctx, s.bucket, key, minio.RemoveObjectOptions{}); err != nil {
		return fmt.Errorf("media: %w", err)
	}
	return nil
}

// SignedURL implements Storage: a presigned GET that forces the response headers.
func (s *S3) SignedURL(ctx context.Context, key string, ttl time.Duration, contentType, disposition string) (string, error) {
	if !validKey(key) {
		return "", errors.New("media: invalid key")
	}
	params := url.Values{}
	params.Set("response-content-type", contentType)
	params.Set("response-content-disposition", disposition)
	u, err := s.signer.PresignedGetObject(ctx, s.bucket, key, ttl, params)
	if err != nil {
		return "", fmt.Errorf("media: %w", err)
	}
	return u.String(), nil
}

// Ping checks that the bucket is reachable.
func (s *S3) Ping(ctx context.Context) error {
	ok, err := s.client.BucketExists(ctx, s.bucket)
	if err != nil {
		return fmt.Errorf("media: %w", err)
	}
	if !ok {
		return errors.New("media: bucket does not exist")
	}
	return nil
}
