// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (uploader_id, chat_id, storage_key, mime_type, size, width, height, duration, waveform)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, uploader_id, chat_id, storage_key, mime_type, size, width, height, duration, waveform, created_at
`

type CreateAttachmentParams struct {
	UploaderID *int64
	ChatID     int64
	StorageKey string
	MimeType   string
	Size       int64
	Width      *int32
	Height     *int32
	Duration   *float64
	Waveform   []int16
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.UploaderID,
		arg.ChatID,
		arg.StorageKey,
		arg.MimeType,
		arg.Size,
		arg.Width,
		arg.Height,
		arg.Duration,
		arg.Waveform,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.ChatID,
		&i.StorageKey,
		&i.MimeType,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.Duration,
		&i.Waveform,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :one
DELETE FROM attachments WHERE id = $1 RETURNING storage_key
`

func (q *Queries) DeleteAttachment(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, deleteAttachment, id)
	var storage_key string
	err := row.Scan(&storage_key)
	return storage_key, err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, uploader_id, chat_id, storage_key, mime_type, size, width, height, duration, waveform, created_at FROM attachments WHERE id = $1
`

func (q *Queries) GetAttachment(ctx context.Context, id uuid.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.UploaderID,
		&i.ChatID,
		&i.StorageKey,
		&i.MimeType,
		&i.Size,
		&i.Width,
		&i.Height,
		&i.Duration,
		&i.Waveform,
		&i.CreatedAt,
	)
	return i, err
}

const listAttachmentKeysOfChats = `-- name: ListAttachmentKeysOfChats :many
SELECT storage_key FROM attachments WHERE chat_id = ANY($1::bigint[]) ORDER BY storage_key
`

func (q *Queries) ListAttachmentKeysOfChats(ctx context.Context, chatIds []int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listAttachmentKeysOfChats, chatIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var storage_key string
		if err := rows.Scan(&storage_key); err != nil {
			return nil, err
		}
		items = append(items, storage_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatAttachments = `-- name: ListChatAttachments :many
SELECT id, uploader_id, chat_id, storage_key, mime_type, size, width, height, duration, waveform, created_at FROM attachments
WHERE chat_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListChatAttachmentsParams struct {
	ChatID  int64
	MaxRows int32
}

func (q *Queries) ListChatAttachments(ctx context.Context, arg ListChatAttachmentsParams) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listChatAttachments, arg.ChatID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attachment{}
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.UploaderID,
			&i.ChatID,
			&i.StorageKey,
			&i.MimeType,
			&i.Size,
			&i.Width,
			&i.Height,
			&i.Duration,
			&i.Waveform,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
