// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chats.sql

package sqlcdb

import (
	"context"
)

const addParticipant = `-- name: AddParticipant :one
INSERT INTO participants (chat_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING chat_id, user_id, role, last_read_message_id, joined_at
`

type AddParticipantParams struct {
	ChatID int64
	UserID int64
	Role   string
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, addParticipant, arg.ChatID, arg.UserID, arg.Role)
	var i Participant
	err := row.Scan(
		&i.ChatID,
		&i.UserID,
		&i.Role,
		&i.LastReadMessageID,
		&i.JoinedAt,
	)
	return i, err
}

const deleteChat = `-- name: DeleteChat :execrows
DELETE FROM chats WHERE id = $1
`

func (q *Queries) DeleteChat(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChat, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChat = `-- name: GetChat :one
SELECT id, type, name, description, avatar_url, direct_key, created_by, created_at, updated_at FROM chats WHERE id = $1
`

func (q *Queries) GetChat(ctx context.Context, id int64) (Chat, error) {
	row := q.db.QueryRow(ctx, getChat, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.DirectKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDirectChat = `-- name: GetDirectChat :one
SELECT id, type, name, description, avatar_url, direct_key, created_by, created_at, updated_at FROM chats WHERE direct_key = $1
`

func (q *Queries) GetDirectChat(ctx context.Context, directKey *string) (Chat, error) {
	row := q.db.QueryRow(ctx, getDirectChat, directKey)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.DirectKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParticipant = `-- name: GetParticipant :one
SELECT chat_id, user_id, role, last_read_message_id, joined_at FROM participants WHERE chat_id = $1 AND user_id = $2
`

type GetParticipantParams struct {
	ChatID int64
	UserID int64
}

func (q *Queries) GetParticipant(ctx context.Context, arg GetParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, getParticipant, arg.ChatID, arg.UserID)
	var i Participant
	err := row.Scan(
		&i.ChatID,
		&i.UserID,
		&i.Role,
		&i.LastReadMessageID,
		&i.JoinedAt,
	)
	return i, err
}

const insertDirectChat = `-- name: InsertDirectChat :one
INSERT INTO chats (type, direct_key, created_by)
VALUES ('direct', $1, $2)
ON CONFLICT (direct_key) DO NOTHING
RETURNING id, type, name, description, avatar_url, direct_key, created_by, created_at, updated_at
`

type InsertDirectChatParams struct {
	DirectKey *string
	CreatedBy *int64
}

// Does nothing (and returns no row) when the pair already has a chat.
func (q *Queries) InsertDirectChat(ctx context.Context, arg InsertDirectChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, insertDirectChat, arg.DirectKey, arg.CreatedBy)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.DirectKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertGroupChat = `-- name: InsertGroupChat :one
INSERT INTO chats (type, name, description, avatar_url, created_by)
VALUES ('group', $1, $2, $3, $4)
RETURNING id, type, name, description, avatar_url, direct_key, created_by, created_at, updated_at
`

type InsertGroupChatParams struct {
	Name        *string
	Description string
	AvatarUrl   *string
	CreatedBy   *int64
}

func (q *Queries) InsertGroupChat(ctx context.Context, arg InsertGroupChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, insertGroupChat,
		arg.Name,
		arg.Description,
		arg.AvatarUrl,
		arg.CreatedBy,
	)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.DirectKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDirectChatIDsOfUser = `-- name: ListDirectChatIDsOfUser :many
SELECT c.id
FROM chats c
JOIN participants p ON p.chat_id = c.id
WHERE p.user_id = $1 AND c.type = 'direct'
ORDER BY c.id
FOR UPDATE OF c
`

func (q *Queries) ListDirectChatIDsOfUser(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listDirectChatIDsOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnedGroupIDs = `-- name: ListOwnedGroupIDs :many
SELECT c.id
FROM chats c
JOIN participants p ON p.chat_id = c.id
WHERE p.user_id = $1 AND p.role = 'owner' AND c.type = 'group'
ORDER BY c.id
FOR UPDATE OF c
`

func (q *Queries) ListOwnedGroupIDs(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listOwnedGroupIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipants = `-- name: ListParticipants :many
SELECT chat_id, user_id, role, last_read_message_id, joined_at FROM participants WHERE chat_id = $1 ORDER BY joined_at, user_id
`

func (q *Queries) ListParticipants(ctx context.Context, chatID int64) ([]Participant, error) {
	rows, err := q.db.Query(ctx, listParticipants, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Participant{}
	for rows.Next() {
		var i Participant
		if err := rows.Scan(
			&i.ChatID,
			&i.UserID,
			&i.Role,
			&i.LastReadMessageID,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserChats = `-- name: ListUserChats :many
SELECT c.id, c.type, c.name, c.description, c.avatar_url, c.direct_key, c.created_by, c.created_at, c.updated_at
FROM chats c
JOIN participants p ON p.chat_id = c.id
WHERE p.user_id = $1
ORDER BY c.updated_at DESC, c.id DESC
LIMIT $2
`

type ListUserChatsParams struct {
	UserID  int64
	MaxRows int32
}

func (q *Queries) ListUserChats(ctx context.Context, arg ListUserChatsParams) ([]Chat, error) {
	rows, err := q.db.Query(ctx, listUserChats, arg.UserID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chat{}
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Description,
			&i.AvatarUrl,
			&i.DirectKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockChat = `-- name: LockChat :one
SELECT id, type, name, description, avatar_url, direct_key, created_by, created_at, updated_at FROM chats WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockChat(ctx context.Context, id int64) (Chat, error) {
	row := q.db.QueryRow(ctx, lockChat, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.DirectKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockChatsOfUser = `-- name: LockChatsOfUser :many
SELECT c.id
FROM chats c
WHERE c.created_by = $1::bigint
   OR EXISTS (SELECT 1 FROM participants p WHERE p.chat_id = c.id AND p.user_id = $1::bigint)
   OR EXISTS (SELECT 1 FROM attachments a WHERE a.chat_id = c.id AND a.uploader_id = $1::bigint)
ORDER BY c.id
FOR UPDATE OF c
`

// Chats that reference the user as member, creator or uploader: deleting the user also rewrites
// chats.created_by and attachments.uploader_id (SET NULL), so those chats must be locked in one id order
// or two deletions can deadlock.
func (q *Queries) LockChatsOfUser(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, lockChatsOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockParticipant = `-- name: LockParticipant :one
SELECT chat_id, user_id, role, last_read_message_id, joined_at FROM participants WHERE chat_id = $1 AND user_id = $2 FOR UPDATE
`

type LockParticipantParams struct {
	ChatID int64
	UserID int64
}

func (q *Queries) LockParticipant(ctx context.Context, arg LockParticipantParams) (Participant, error) {
	row := q.db.QueryRow(ctx, lockParticipant, arg.ChatID, arg.UserID)
	var i Participant
	err := row.Scan(
		&i.ChatID,
		&i.UserID,
		&i.Role,
		&i.LastReadMessageID,
		&i.JoinedAt,
	)
	return i, err
}

const markRead = `-- name: MarkRead :execrows
UPDATE participants
SET last_read_message_id = GREATEST(COALESCE(last_read_message_id, 0), $1::bigint)
WHERE chat_id = $2 AND user_id = $3
`

type MarkReadParams struct {
	MessageID int64
	ChatID    int64
	UserID    int64
}

// The read marker only moves forward.
func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRead, arg.MessageID, arg.ChatID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const nextOwnerCandidate = `-- name: NextOwnerCandidate :one
SELECT user_id
FROM participants
WHERE chat_id = $1 AND user_id <> $2
ORDER BY CASE role WHEN 'admin' THEN 0 WHEN 'moderator' THEN 1 ELSE 2 END, joined_at, user_id
LIMIT 1
`

type NextOwnerCandidateParams struct {
	ChatID        int64
	LeavingUserID int64
}

// Who inherits a group when its owner leaves: admins first, then moderators, then the longest member.
func (q *Queries) NextOwnerCandidate(ctx context.Context, arg NextOwnerCandidateParams) (int64, error) {
	row := q.db.QueryRow(ctx, nextOwnerCandidate, arg.ChatID, arg.LeavingUserID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const removeParticipant = `-- name: RemoveParticipant :execrows
DELETE FROM participants WHERE chat_id = $1 AND user_id = $2
`

type RemoveParticipantParams struct {
	ChatID int64
	UserID int64
}

func (q *Queries) RemoveParticipant(ctx context.Context, arg RemoveParticipantParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeParticipant, arg.ChatID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setParticipantRole = `-- name: SetParticipantRole :execrows
UPDATE participants SET role = $1 WHERE chat_id = $2 AND user_id = $3
`

type SetParticipantRoleParams struct {
	Role   string
	ChatID int64
	UserID int64
}

func (q *Queries) SetParticipantRole(ctx context.Context, arg SetParticipantRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, setParticipantRole, arg.Role, arg.ChatID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
