// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chatlist.sql

package sqlcdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const closeDirectRequests = `-- name: CloseDirectRequests :many
UPDATE approval_requests
SET status = 'approved', responded_at = now()
WHERE type = 'direct_message' AND status = 'pending'
  AND ((requester_id = $1 AND recipient_id = $2) OR (requester_id = $2 AND recipient_id = $1))
RETURNING id, type, requester_id, recipient_id, status, message_text, chat_id, created_at, responded_at
`

type CloseDirectRequestsParams struct {
	A int64
	B int64
}

// The pair has a chat now: pending direct-message requests between them, in either direction, are done.
func (q *Queries) CloseDirectRequests(ctx context.Context, arg CloseDirectRequestsParams) ([]ApprovalRequest, error) {
	rows, err := q.db.Query(ctx, closeDirectRequests, arg.A, arg.B)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalRequest{}
	for rows.Next() {
		var i ApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.RequesterID,
			&i.RecipientID,
			&i.Status,
			&i.MessageText,
			&i.ChatID,
			&i.CreatedAt,
			&i.RespondedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countPins = `-- name: CountPins :one
SELECT count(*) FROM user_chat_pins pin
JOIN participants p ON p.chat_id = pin.chat_id AND p.user_id = pin.user_id
WHERE pin.user_id = $1
`

// Pins of chats the user is still in (pins of chats they left do not use up the limit).
func (q *Queries) CountPins(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countPins, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDirectRequest = `-- name: CreateDirectRequest :one
INSERT INTO approval_requests (type, requester_id, recipient_id, message_text)
VALUES ('direct_message', $1, $2, $3)
ON CONFLICT (requester_id, recipient_id) WHERE status = 'pending' AND type = 'direct_message'
DO UPDATE SET message_text = COALESCE(approval_requests.message_text, EXCLUDED.message_text)
RETURNING id, type, requester_id, recipient_id, status, message_text, chat_id, created_at, responded_at, (xmax = 0) AS created
`

type CreateDirectRequestParams struct {
	RequesterID int64
	RecipientID int64
	MessageText *string
}

type CreateDirectRequestRow struct {
	ID          int64
	Type        string
	RequesterID int64
	RecipientID int64
	Status      string
	MessageText *string
	ChatID      *int64
	CreatedAt   time.Time
	RespondedAt *time.Time
	Created     bool
}

// A pending request of the same pair is reused (the unique index allows one), so asking twice is harmless.
func (q *Queries) CreateDirectRequest(ctx context.Context, arg CreateDirectRequestParams) (CreateDirectRequestRow, error) {
	row := q.db.QueryRow(ctx, createDirectRequest, arg.RequesterID, arg.RecipientID, arg.MessageText)
	var i CreateDirectRequestRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.RequesterID,
		&i.RecipientID,
		&i.Status,
		&i.MessageText,
		&i.ChatID,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.Created,
	)
	return i, err
}

const getApprovalRequest = `-- name: GetApprovalRequest :one
SELECT id, type, requester_id, recipient_id, status, message_text, chat_id, created_at, responded_at FROM approval_requests WHERE id = $1
`

func (q *Queries) GetApprovalRequest(ctx context.Context, id int64) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, getApprovalRequest, id)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.RequesterID,
		&i.RecipientID,
		&i.Status,
		&i.MessageText,
		&i.ChatID,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const getChatEntry = `-- name: GetChatEntry :one
SELECT c.id, c.type, c.name, c.description, c.avatar_url, c.direct_key, c.created_by, c.created_at, c.updated_at, c.avatar_attachment_id, c.last_message_id, c.last_activity_at, p.role, p.last_read_message_id, pin.pinned_at,
       COALESCE(pin.pinned_at, c.last_activity_at)::timestamptz AS sort_at
FROM participants p
JOIN chats c ON c.id = p.chat_id
LEFT JOIN user_chat_pins pin ON pin.user_id = p.user_id AND pin.chat_id = p.chat_id
WHERE p.user_id = $1 AND p.chat_id = $2
`

type GetChatEntryParams struct {
	UserID int64
	ChatID int64
}

type GetChatEntryRow struct {
	ID                 int64
	Type               string
	Name               *string
	Description        string
	AvatarUrl          *string
	DirectKey          *string
	CreatedBy          *int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
	AvatarAttachmentID *uuid.UUID
	LastMessageID      *int64
	LastActivityAt     time.Time
	Role               string
	LastReadMessageID  *int64
	PinnedAt           *time.Time
	SortAt             time.Time
}

func (q *Queries) GetChatEntry(ctx context.Context, arg GetChatEntryParams) (GetChatEntryRow, error) {
	row := q.db.QueryRow(ctx, getChatEntry, arg.UserID, arg.ChatID)
	var i GetChatEntryRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.DirectKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarAttachmentID,
		&i.LastMessageID,
		&i.LastActivityAt,
		&i.Role,
		&i.LastReadMessageID,
		&i.PinnedAt,
		&i.SortAt,
	)
	return i, err
}

const listChatEntries = `-- name: ListChatEntries :many
SELECT c.id, c.type, c.name, c.description, c.avatar_url, c.direct_key, c.created_by, c.created_at, c.updated_at, c.avatar_attachment_id, c.last_message_id, c.last_activity_at, p.role, p.last_read_message_id, pin.pinned_at,
       COALESCE(pin.pinned_at, c.last_activity_at)::timestamptz AS sort_at
FROM participants p
JOIN chats c ON c.id = p.chat_id
LEFT JOIN user_chat_pins pin ON pin.user_id = p.user_id AND pin.chat_id = p.chat_id
WHERE p.user_id = $1
  AND (
    $2::bigint IS NULL
    OR (pin.pinned_at IS NULL)::int > $3::int
    OR ((pin.pinned_at IS NULL)::int = $3::int AND (
          COALESCE(pin.pinned_at, c.last_activity_at) < $4::timestamptz
          OR (COALESCE(pin.pinned_at, c.last_activity_at) = $4::timestamptz AND c.id < $2::bigint)))
  )
ORDER BY (pin.pinned_at IS NULL), COALESCE(pin.pinned_at, c.last_activity_at) DESC, c.id DESC
LIMIT $5
`

type ListChatEntriesParams struct {
	UserID        int64
	AfterChatID   *int64
	AfterUnpinned *int32
	AfterSortAt   *time.Time
	MaxRows       int32
}

type ListChatEntriesRow struct {
	ID                 int64
	Type               string
	Name               *string
	Description        string
	AvatarUrl          *string
	DirectKey          *string
	CreatedBy          *int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
	AvatarAttachmentID *uuid.UUID
	LastMessageID      *int64
	LastActivityAt     time.Time
	Role               string
	LastReadMessageID  *int64
	PinnedAt           *time.Time
	SortAt             time.Time
}

// A user's chats: pinned ones first (most recently pinned first), then by last activity, then by id. The
// cursor is the last entry of the previous page: (pinned, sort time, chat id).
func (q *Queries) ListChatEntries(ctx context.Context, arg ListChatEntriesParams) ([]ListChatEntriesRow, error) {
	rows, err := q.db.Query(ctx, listChatEntries,
		arg.UserID,
		arg.AfterChatID,
		arg.AfterUnpinned,
		arg.AfterSortAt,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChatEntriesRow{}
	for rows.Next() {
		var i ListChatEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Name,
			&i.Description,
			&i.AvatarUrl,
			&i.DirectKey,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvatarAttachmentID,
			&i.LastMessageID,
			&i.LastActivityAt,
			&i.Role,
			&i.LastReadMessageID,
			&i.PinnedAt,
			&i.SortAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOtherParticipants = `-- name: ListOtherParticipants :many
SELECT chat_id, user_id, last_read_message_id, last_read_at
FROM participants
WHERE chat_id = ANY($1::bigint[]) AND user_id <> $2
ORDER BY chat_id, user_id
`

type ListOtherParticipantsParams struct {
	ChatIds []int64
	UserID  int64
}

type ListOtherParticipantsRow struct {
	ChatID            int64
	UserID            int64
	LastReadMessageID *int64
	LastReadAt        *time.Time
}

// The other members of the chats (the peers of direct chats), with their read markers.
func (q *Queries) ListOtherParticipants(ctx context.Context, arg ListOtherParticipantsParams) ([]ListOtherParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listOtherParticipants, arg.ChatIds, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOtherParticipantsRow{}
	for rows.Next() {
		var i ListOtherParticipantsRow
		if err := rows.Scan(
			&i.ChatID,
			&i.UserID,
			&i.LastReadMessageID,
			&i.LastReadAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRequests = `-- name: ListPendingRequests :many
SELECT id, type, requester_id, recipient_id, status, message_text, chat_id, created_at, responded_at FROM approval_requests
WHERE recipient_id = $1 AND status = 'pending' AND type = 'direct_message'
  AND ($2::bigint IS NULL OR id < $2::bigint)
ORDER BY id DESC
LIMIT $3
`

type ListPendingRequestsParams struct {
	RecipientID int64
	BeforeID    *int64
	MaxRows     int32
}

// The recipient's inbox of direct-message requests, newest first; the cursor is the last request id. (Group
// invitations are answered with the group endpoints.)
func (q *Queries) ListPendingRequests(ctx context.Context, arg ListPendingRequestsParams) ([]ApprovalRequest, error) {
	rows, err := q.db.Query(ctx, listPendingRequests, arg.RecipientID, arg.BeforeID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApprovalRequest{}
	for rows.Next() {
		var i ApprovalRequest
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.RequesterID,
			&i.RecipientID,
			&i.Status,
			&i.MessageText,
			&i.ChatID,
			&i.CreatedAt,
			&i.RespondedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockApprovalRequest = `-- name: LockApprovalRequest :one
SELECT id, type, requester_id, recipient_id, status, message_text, chat_id, created_at, responded_at FROM approval_requests WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockApprovalRequest(ctx context.Context, id int64) (ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, lockApprovalRequest, id)
	var i ApprovalRequest
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.RequesterID,
		&i.RecipientID,
		&i.Status,
		&i.MessageText,
		&i.ChatID,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const lockDirectPair = `-- name: LockDirectPair :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// Serializes everything that opens a direct chat of a pair or asks for one (key: the direct_key), so a
// request cannot be made while the chat is being opened.
func (q *Queries) LockDirectPair(ctx context.Context, directKey string) error {
	_, err := q.db.Exec(ctx, lockDirectPair, directKey)
	return err
}

const pinChat = `-- name: PinChat :execrows
INSERT INTO user_chat_pins (user_id, chat_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type PinChatParams struct {
	UserID int64
	ChatID int64
}

func (q *Queries) PinChat(ctx context.Context, arg PinChatParams) (int64, error) {
	result, err := q.db.Exec(ctx, pinChat, arg.UserID, arg.ChatID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const respondToRequest = `-- name: RespondToRequest :execrows
UPDATE approval_requests SET status = $1, responded_at = now() WHERE id = $2 AND status = 'pending'
`

type RespondToRequestParams struct {
	Status string
	ID     int64
}

func (q *Queries) RespondToRequest(ctx context.Context, arg RespondToRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, respondToRequest, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchChatActivity = `-- name: TouchChatActivity :exec
UPDATE chats
SET last_message_id = $1::bigint, last_activity_at = $2
WHERE id = $3 AND (last_message_id IS NULL OR last_message_id < $1::bigint)
`

type TouchChatActivityParams struct {
	MessageID int64
	At        time.Time
	ChatID    int64
}

// A new message: the chat moves to the top of its members' lists. Never moves back for an older id.
func (q *Queries) TouchChatActivity(ctx context.Context, arg TouchChatActivityParams) error {
	_, err := q.db.Exec(ctx, touchChatActivity, arg.MessageID, arg.At, arg.ChatID)
	return err
}

const unpinChat = `-- name: UnpinChat :execrows
DELETE FROM user_chat_pins WHERE user_id = $1 AND chat_id = $2
`

type UnpinChatParams struct {
	UserID int64
	ChatID int64
}

func (q *Queries) UnpinChat(ctx context.Context, arg UnpinChatParams) (int64, error) {
	result, err := q.db.Exec(ctx, unpinChat, arg.UserID, arg.ChatID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
