// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlcdb

import (
	"context"
	"time"
)

const closeGroupInvites = `-- name: CloseGroupInvites :execrows
UPDATE approval_requests SET status = 'approved', responded_at = now()
WHERE chat_id = $1 AND recipient_id = $2 AND type = 'group_invite' AND status = 'pending'
`

type CloseGroupInvitesParams struct {
	ChatID      *int64
	RecipientID int64
}

// The user is in the group now: their pending invitations to it are settled.
func (q *Queries) CloseGroupInvites(ctx context.Context, arg CloseGroupInvitesParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeGroupInvites, arg.ChatID, arg.RecipientID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createGroupInvite = `-- name: CreateGroupInvite :one
INSERT INTO approval_requests (type, requester_id, recipient_id, chat_id)
VALUES ('group_invite', $1, $2, $3)
ON CONFLICT (requester_id, recipient_id, chat_id) WHERE status = 'pending' AND type = 'group_invite'
DO UPDATE SET created_at = approval_requests.created_at
RETURNING id, type, requester_id, recipient_id, status, message_text, chat_id, created_at, responded_at, (xmax = 0) AS created
`

type CreateGroupInviteParams struct {
	RequesterID int64
	RecipientID int64
	ChatID      *int64
}

type CreateGroupInviteRow struct {
	ID          int64
	Type        string
	RequesterID int64
	RecipientID int64
	Status      string
	MessageText *string
	ChatID      *int64
	CreatedAt   time.Time
	RespondedAt *time.Time
	Created     bool
}

// A pending invitation of the same requester, recipient and group is reused.
func (q *Queries) CreateGroupInvite(ctx context.Context, arg CreateGroupInviteParams) (CreateGroupInviteRow, error) {
	row := q.db.QueryRow(ctx, createGroupInvite, arg.RequesterID, arg.RecipientID, arg.ChatID)
	var i CreateGroupInviteRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.RequesterID,
		&i.RecipientID,
		&i.Status,
		&i.MessageText,
		&i.ChatID,
		&i.CreatedAt,
		&i.RespondedAt,
		&i.Created,
	)
	return i, err
}

const updateGroupInfo = `-- name: UpdateGroupInfo :one
UPDATE chats
SET name = COALESCE($1, name),
    description = CASE WHEN $2::bool THEN COALESCE($3, '') ELSE description END
WHERE id = $4 AND type = 'group'
RETURNING id, type, name, description, avatar_url, direct_key, created_by, created_at, updated_at, avatar_attachment_id, last_message_id, last_activity_at
`

type UpdateGroupInfoParams struct {
	Name           *string
	SetDescription bool
	Description    *string
	ID             int64
}

// Changes only what is given: the name, and the description when set_description (null clears it).
func (q *Queries) UpdateGroupInfo(ctx context.Context, arg UpdateGroupInfoParams) (Chat, error) {
	row := q.db.QueryRow(ctx, updateGroupInfo,
		arg.Name,
		arg.SetDescription,
		arg.Description,
		arg.ID,
	)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Name,
		&i.Description,
		&i.AvatarUrl,
		&i.DirectKey,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarAttachmentID,
		&i.LastMessageID,
		&i.LastActivityAt,
	)
	return i, err
}
