// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type ApprovalRequest struct {
	ID          int64
	Type        string
	RequesterID int64
	RecipientID int64
	Status      string
	MessageText *string
	ChatID      *int64
	CreatedAt   time.Time
	RespondedAt *time.Time
}

type Attachment struct {
	ID         uuid.UUID
	UploaderID *int64
	ChatID     int64
	StorageKey string
	MimeType   string
	Size       int64
	Width      *int32
	Height     *int32
	Duration   *float64
	Waveform   []int16
	CreatedAt  time.Time
}

type Chat struct {
	ID          int64
	Type        string
	Name        *string
	Description string
	AvatarUrl   *string
	DirectKey   *string
	CreatedBy   *int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Participant struct {
	ChatID            int64
	UserID            int64
	Role              string
	LastReadMessageID *int64
	JoinedAt          time.Time
}

type RecoveryToken struct {
	JtiHash   string
	UserID    int64
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type User struct {
	ID           int64
	Username     string
	DisplayName  string
	PasswordHash string
	AvatarUrl    *string
	Bio          *string
	LastSeenAt   time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type User2faRecoveryCode struct {
	ID        int64
	UserID    int64
	CodeHash  string
	CreatedAt time.Time
	UsedAt    *time.Time
}

type UserAvatarHistory struct {
	ID        int64
	UserID    int64
	AvatarUrl string
	IsCurrent bool
	CreatedAt time.Time
}

type UserBlock struct {
	BlockerID int64
	BlockedID int64
	CreatedAt time.Time
}

type UserChatPin struct {
	UserID   int64
	ChatID   int64
	PinnedAt time.Time
}

type UserContactName struct {
	OwnerID     int64
	TargetID    int64
	DisplayName string
	UpdatedAt   time.Time
}

type UserPrivacyException struct {
	OwnerID      int64
	SettingKey   string
	TargetUserID int64
	Effect       string
	CreatedAt    time.Time
}

type UserPrivacySetting struct {
	UserID              int64
	AvatarVisibility    string
	ProfileVisibility   string
	PresenceVisibility  string
	ReadReceiptsEnabled bool
	DirectMessages      string
	GroupInvites        string
	SearchVisibility    string
}

type UserRecoveryShare struct {
	UserID                 int64
	EncryptedCloudPart     *string
	Salt                   []byte
	VerificationCiphertext *string
}

type UserSecurityEvent struct {
	ID        int64
	UserID    int64
	EventType string
	IpAddress *netip.Addr
	UserAgent *string
	Details   []byte
	CreatedAt time.Time
}

type UserSecuritySetting struct {
	UserID                 int64
	SessionDurationDays    int32
	TwoFactorEnabled       bool
	TwoFactorSecret        *string
	PendingTwoFactorSecret *string
	UpdatedAt              time.Time
}

type UserSession struct {
	ID                       uuid.UUID
	UserID                   int64
	RefreshTokenHash         string
	UserAgent                *string
	IpAddress                *netip.Addr
	CreatedAt                time.Time
	LastActiveAt             time.Time
	ExpiresAt                time.Time
	RevokedAt                *time.Time
	PreviousRefreshTokenHash *string
	RotatedAt                *time.Time
}
