// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery.sql

package sqlcdb

import (
	"context"
	"time"
)

const consumeRecoveryToken = `-- name: ConsumeRecoveryToken :one
UPDATE recovery_tokens SET used_at = now()
WHERE jti_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING user_id
`

// Single use: the first caller gets the user, everyone else (and expired tokens) get no row.
func (q *Queries) ConsumeRecoveryToken(ctx context.Context, jtiHash string) (int64, error) {
	row := q.db.QueryRow(ctx, consumeRecoveryToken, jtiHash)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const createRecoveryToken = `-- name: CreateRecoveryToken :exec
INSERT INTO recovery_tokens (jti_hash, user_id, expires_at) VALUES ($1, $2, $3)
`

type CreateRecoveryTokenParams struct {
	JtiHash   string
	UserID    int64
	ExpiresAt time.Time
}

func (q *Queries) CreateRecoveryToken(ctx context.Context, arg CreateRecoveryTokenParams) error {
	_, err := q.db.Exec(ctx, createRecoveryToken, arg.JtiHash, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteStaleRecoveryTokens = `-- name: DeleteStaleRecoveryTokens :execrows
DELETE FROM recovery_tokens WHERE expires_at < now() - interval '1 day'
`

func (q *Queries) DeleteStaleRecoveryTokens(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleRecoveryTokens)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
