// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: security_events.sql

package sqlcdb

import (
	"context"
	"net/netip"
)

const listSecurityEvents = `-- name: ListSecurityEvents :many
SELECT id, user_id, event_type, ip_address, user_agent, details, created_at
FROM user_security_events
WHERE user_id = $1 AND ($2::bigint IS NULL OR id < $2::bigint)
ORDER BY id DESC
LIMIT $3
`

type ListSecurityEventsParams struct {
	UserID   int64
	BeforeID *int64
	MaxRows  int32
}

// Newest first; pass the id of the last row of the previous page as before_id.
func (q *Queries) ListSecurityEvents(ctx context.Context, arg ListSecurityEventsParams) ([]UserSecurityEvent, error) {
	rows, err := q.db.Query(ctx, listSecurityEvents, arg.UserID, arg.BeforeID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSecurityEvent{}
	for rows.Next() {
		var i UserSecurityEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.IpAddress,
			&i.UserAgent,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSecurityEvent = `-- name: RecordSecurityEvent :one
INSERT INTO user_security_events (user_id, event_type, ip_address, user_agent, details)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, event_type, ip_address, user_agent, details, created_at
`

type RecordSecurityEventParams struct {
	UserID    int64
	EventType string
	IpAddress *netip.Addr
	UserAgent *string
	Details   []byte
}

func (q *Queries) RecordSecurityEvent(ctx context.Context, arg RecordSecurityEventParams) (UserSecurityEvent, error) {
	row := q.db.QueryRow(ctx, recordSecurityEvent,
		arg.UserID,
		arg.EventType,
		arg.IpAddress,
		arg.UserAgent,
		arg.Details,
	)
	var i UserSecurityEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.IpAddress,
		&i.UserAgent,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}
