// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: security_settings.sql

package sqlcdb

import (
	"context"
)

const countUnusedRecoveryCodes = `-- name: CountUnusedRecoveryCodes :one
SELECT count(*) FROM user_2fa_recovery_codes WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) CountUnusedRecoveryCodes(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnusedRecoveryCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM user_2fa_recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodes, userID)
	return err
}

const disableTwoFactor = `-- name: DisableTwoFactor :execrows
UPDATE user_security_settings
SET two_factor_enabled = FALSE, two_factor_secret = NULL, pending_two_factor_secret = NULL
WHERE user_id = $1
`

func (q *Queries) DisableTwoFactor(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.Exec(ctx, disableTwoFactor, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enableTwoFactor = `-- name: EnableTwoFactor :execrows
UPDATE user_security_settings
SET two_factor_enabled = TRUE,
    two_factor_secret = pending_two_factor_secret,
    pending_two_factor_secret = NULL
WHERE user_id = $1 AND NOT two_factor_enabled AND pending_two_factor_secret = $2
`

type EnableTwoFactorParams struct {
	UserID        int64
	PendingSecret *string
}

// Compare-and-swap on the pending secret, so a second setup between verify and confirm cannot be confirmed by accident.
func (q *Queries) EnableTwoFactor(ctx context.Context, arg EnableTwoFactorParams) (int64, error) {
	result, err := q.db.Exec(ctx, enableTwoFactor, arg.UserID, arg.PendingSecret)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureSecuritySettings = `-- name: EnsureSecuritySettings :exec
INSERT INTO user_security_settings (user_id) VALUES ($1) ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) EnsureSecuritySettings(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, ensureSecuritySettings, userID)
	return err
}

const getSecuritySettings = `-- name: GetSecuritySettings :one
SELECT user_id, session_duration_days, two_factor_enabled, two_factor_secret, pending_two_factor_secret, updated_at FROM user_security_settings WHERE user_id = $1
`

func (q *Queries) GetSecuritySettings(ctx context.Context, userID int64) (UserSecuritySetting, error) {
	row := q.db.QueryRow(ctx, getSecuritySettings, userID)
	var i UserSecuritySetting
	err := row.Scan(
		&i.UserID,
		&i.SessionDurationDays,
		&i.TwoFactorEnabled,
		&i.TwoFactorSecret,
		&i.PendingTwoFactorSecret,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRecoveryCodes = `-- name: InsertRecoveryCodes :exec
INSERT INTO user_2fa_recovery_codes (user_id, code_hash)
SELECT $1::bigint, unnest($2::text[])
`

type InsertRecoveryCodesParams struct {
	UserID     int64
	CodeHashes []string
}

func (q *Queries) InsertRecoveryCodes(ctx context.Context, arg InsertRecoveryCodesParams) error {
	_, err := q.db.Exec(ctx, insertRecoveryCodes, arg.UserID, arg.CodeHashes)
	return err
}

const setPendingTwoFactorSecret = `-- name: SetPendingTwoFactorSecret :execrows
UPDATE user_security_settings SET pending_two_factor_secret = $1
WHERE user_id = $2 AND NOT two_factor_enabled
`

type SetPendingTwoFactorSecretParams struct {
	Secret *string
	UserID int64
}

func (q *Queries) SetPendingTwoFactorSecret(ctx context.Context, arg SetPendingTwoFactorSecretParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPendingTwoFactorSecret, arg.Secret, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSessionDuration = `-- name: SetSessionDuration :execrows
UPDATE user_security_settings SET session_duration_days = $1 WHERE user_id = $2
`

type SetSessionDurationParams struct {
	Days   int32
	UserID int64
}

func (q *Queries) SetSessionDuration(ctx context.Context, arg SetSessionDurationParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSessionDuration, arg.Days, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const useRecoveryCode = `-- name: UseRecoveryCode :execrows
UPDATE user_2fa_recovery_codes SET used_at = now()
WHERE user_id = $1 AND code_hash = $2 AND used_at IS NULL
`

type UseRecoveryCodeParams struct {
	UserID   int64
	CodeHash string
}

func (q *Queries) UseRecoveryCode(ctx context.Context, arg UseRecoveryCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, useRecoveryCode, arg.UserID, arg.CodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
