// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcdb

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO user_sessions (user_id, refresh_token_hash, user_agent, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, refresh_token_hash, user_agent, ip_address, created_at, last_active_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	UserID           int64
	RefreshTokenHash string
	UserAgent        *string
	IpAddress        *netip.Addr
	ExpiresAt        time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteEndedSessions = `-- name: DeleteEndedSessions :execrows
DELETE FROM user_sessions WHERE id IN (
    SELECT id FROM user_sessions
    WHERE expires_at < $1::timestamptz OR revoked_at < $1::timestamptz
    LIMIT $2::int
)
`

type DeleteEndedSessionsParams struct {
	Cutoff time.Time
	Batch  int32
}

// Deleting a session cascades to its rotated refresh hashes.
func (q *Queries) DeleteEndedSessions(ctx context.Context, arg DeleteEndedSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEndedSessions, arg.Cutoff, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldRotatedTokens = `-- name: DeleteOldRotatedTokens :execrows
DELETE FROM user_session_rotated_tokens WHERE token_hash IN (
    SELECT token_hash FROM user_session_rotated_tokens
    WHERE rotated_at < $1::timestamptz
    LIMIT $2::int
)
`

type DeleteOldRotatedTokensParams struct {
	Cutoff time.Time
	Batch  int32
}

func (q *Queries) DeleteOldRotatedTokens(ctx context.Context, arg DeleteOldRotatedTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldRotatedTokens, arg.Cutoff, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRotatedToken = `-- name: GetRotatedToken :one
SELECT session_id, rotated_at FROM user_session_rotated_tokens WHERE token_hash = $1
`

type GetRotatedTokenRow struct {
	SessionID uuid.UUID
	RotatedAt time.Time
}

func (q *Queries) GetRotatedToken(ctx context.Context, hash string) (GetRotatedTokenRow, error) {
	row := q.db.QueryRow(ctx, getRotatedToken, hash)
	var i GetRotatedTokenRow
	err := row.Scan(&i.SessionID, &i.RotatedAt)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, created_at, last_active_at, expires_at, revoked_at FROM user_sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByRefreshHash = `-- name: GetSessionByRefreshHash :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, created_at, last_active_at, expires_at, revoked_at FROM user_sessions WHERE refresh_token_hash = $1
`

func (q *Queries) GetSessionByRefreshHash(ctx context.Context, hash string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshHash, hash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, created_at, last_active_at, expires_at, revoked_at FROM user_sessions
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
ORDER BY last_active_at DESC, created_at DESC
`

func (q *Queries) ListActiveSessions(ctx context.Context, userID int64) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserSession{}
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.UserAgent,
			&i.IpAddress,
			&i.CreatedAt,
			&i.LastActiveAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSession = `-- name: LockSession :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, created_at, last_active_at, expires_at, revoked_at FROM user_sessions WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockSession(ctx context.Context, id uuid.UUID) (UserSession, error) {
	row := q.db.QueryRow(ctx, lockSession, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const lockSessionByRefreshHash = `-- name: LockSessionByRefreshHash :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, created_at, last_active_at, expires_at, revoked_at FROM user_sessions WHERE refresh_token_hash = $1 FOR UPDATE
`

func (q *Queries) LockSessionByRefreshHash(ctx context.Context, hash string) (UserSession, error) {
	row := q.db.QueryRow(ctx, lockSessionByRefreshHash, hash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const recordRotatedToken = `-- name: RecordRotatedToken :exec
INSERT INTO user_session_rotated_tokens (token_hash, session_id) VALUES ($1, $2)
`

type RecordRotatedTokenParams struct {
	TokenHash string
	SessionID uuid.UUID
}

func (q *Queries) RecordRotatedToken(ctx context.Context, arg RecordRotatedTokenParams) error {
	_, err := q.db.Exec(ctx, recordRotatedToken, arg.TokenHash, arg.SessionID)
	return err
}

const revokeAllSessions = `-- name: RevokeAllSessions :many
UPDATE user_sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL RETURNING id
`

func (q *Queries) RevokeAllSessions(ctx context.Context, userID int64) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeAllSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOtherSessions = `-- name: RevokeOtherSessions :many
UPDATE user_sessions SET revoked_at = now()
WHERE user_id = $1 AND id <> $2 AND revoked_at IS NULL
RETURNING id
`

type RevokeOtherSessionsParams struct {
	UserID int64
	KeepID uuid.UUID
}

func (q *Queries) RevokeOtherSessions(ctx context.Context, arg RevokeOtherSessionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeOtherSessions, arg.UserID, arg.KeepID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :many
UPDATE user_sessions SET revoked_at = now()
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
RETURNING id
`

type RevokeSessionParams struct {
	ID     uuid.UUID
	UserID int64
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeSession, arg.ID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSessionByID = `-- name: RevokeSessionByID :many
UPDATE user_sessions SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL RETURNING id
`

func (q *Queries) RevokeSessionByID(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeSessionByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateSession = `-- name: RotateSession :one
UPDATE user_sessions
SET refresh_token_hash = $1,
    last_active_at     = now(),
    expires_at         = $2,
    user_agent         = COALESCE($3::text, user_agent),
    ip_address         = COALESCE($4::inet, ip_address)
WHERE id = $5
RETURNING id, user_id, refresh_token_hash, user_agent, ip_address, created_at, last_active_at, expires_at, revoked_at
`

type RotateSessionParams struct {
	NewHash   string
	ExpiresAt time.Time
	UserAgent *string
	IpAddress *netip.Addr
	ID        uuid.UUID
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, rotateSession,
		arg.NewHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
		arg.ID,
	)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.CreatedAt,
		&i.LastActiveAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :execrows
UPDATE user_sessions SET last_active_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, touchSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
