// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: social.sql

package sqlcdb

import (
	"context"
	"time"
)

const blockUser = `-- name: BlockUser :exec
INSERT INTO user_blocks (blocker_id, blocked_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type BlockUserParams struct {
	BlockerID int64
	BlockedID int64
}

func (q *Queries) BlockUser(ctx context.Context, arg BlockUserParams) error {
	_, err := q.db.Exec(ctx, blockUser, arg.BlockerID, arg.BlockedID)
	return err
}

const blockedEither = `-- name: BlockedEither :one
SELECT EXISTS (
    SELECT 1 FROM user_blocks
    WHERE (blocker_id = $1 AND blocked_id = $2) OR (blocker_id = $2 AND blocked_id = $1)
)
`

type BlockedEitherParams struct {
	A int64
	B int64
}

// Whether a blocked b or b blocked a.
func (q *Queries) BlockedEither(ctx context.Context, arg BlockedEitherParams) (bool, error) {
	row := q.db.QueryRow(ctx, blockedEither, arg.A, arg.B)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteContactName = `-- name: DeleteContactName :execrows
DELETE FROM user_contact_names WHERE owner_id = $1 AND target_id = $2
`

type DeleteContactNameParams struct {
	OwnerID  int64
	TargetID int64
}

func (q *Queries) DeleteContactName(ctx context.Context, arg DeleteContactNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContactName, arg.OwnerID, arg.TargetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePrivacyException = `-- name: DeletePrivacyException :execrows
DELETE FROM user_privacy_exceptions WHERE owner_id = $1 AND setting_key = $2 AND target_user_id = $3
`

type DeletePrivacyExceptionParams struct {
	OwnerID      int64
	SettingKey   string
	TargetUserID int64
}

func (q *Queries) DeletePrivacyException(ctx context.Context, arg DeletePrivacyExceptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePrivacyException, arg.OwnerID, arg.SettingKey, arg.TargetUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePrivacyExceptionsByEffect = `-- name: DeletePrivacyExceptionsByEffect :exec
DELETE FROM user_privacy_exceptions WHERE owner_id = $1 AND setting_key = $2 AND effect = $3
`

type DeletePrivacyExceptionsByEffectParams struct {
	OwnerID    int64
	SettingKey string
	Effect     string
}

func (q *Queries) DeletePrivacyExceptionsByEffect(ctx context.Context, arg DeletePrivacyExceptionsByEffectParams) error {
	_, err := q.db.Exec(ctx, deletePrivacyExceptionsByEffect, arg.OwnerID, arg.SettingKey, arg.Effect)
	return err
}

const listBlocked = `-- name: ListBlocked :many
SELECT blocker_id, blocked_id, created_at FROM user_blocks WHERE blocker_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListBlocked(ctx context.Context, blockerID int64) ([]UserBlock, error) {
	rows, err := q.db.Query(ctx, listBlocked, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserBlock{}
	for rows.Next() {
		var i UserBlock
		if err := rows.Scan(&i.BlockerID, &i.BlockedID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlockedPage = `-- name: ListBlockedPage :many
SELECT b.blocked_id, b.created_at
FROM user_blocks b
WHERE b.blocker_id = $1
  AND ($2::timestamptz IS NULL OR (b.created_at, b.blocked_id) < ($2::timestamptz, $3::bigint))
ORDER BY b.created_at DESC, b.blocked_id DESC
LIMIT $4
`

type ListBlockedPageParams struct {
	BlockerID    int64
	AfterCreated *time.Time
	AfterID      *int64
	MaxRows      int32
}

type ListBlockedPageRow struct {
	BlockedID int64
	CreatedAt time.Time
}

// The users the blocker blocked, newest block first, after the cursor (the blocked user id of the last row).
func (q *Queries) ListBlockedPage(ctx context.Context, arg ListBlockedPageParams) ([]ListBlockedPageRow, error) {
	rows, err := q.db.Query(ctx, listBlockedPage,
		arg.BlockerID,
		arg.AfterCreated,
		arg.AfterID,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlockedPageRow{}
	for rows.Next() {
		var i ListBlockedPageRow
		if err := rows.Scan(&i.BlockedID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChatIDsOfUser = `-- name: ListChatIDsOfUser :many
SELECT chat_id FROM participants WHERE user_id = $1
`

func (q *Queries) ListChatIDsOfUser(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listChatIDsOfUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var chat_id int64
		if err := rows.Scan(&chat_id); err != nil {
			return nil, err
		}
		items = append(items, chat_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactNames = `-- name: ListContactNames :many
SELECT owner_id, target_id, display_name, updated_at FROM user_contact_names WHERE owner_id = $1 AND target_id = ANY($2::BIGINT[])
`

type ListContactNamesParams struct {
	OwnerID   int64
	TargetIds []int64
}

func (q *Queries) ListContactNames(ctx context.Context, arg ListContactNamesParams) ([]UserContactName, error) {
	rows, err := q.db.Query(ctx, listContactNames, arg.OwnerID, arg.TargetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserContactName{}
	for rows.Next() {
		var i UserContactName
		if err := rows.Scan(
			&i.OwnerID,
			&i.TargetID,
			&i.DisplayName,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContactNamesForTarget = `-- name: ListContactNamesForTarget :many
SELECT owner_id, target_id, display_name, updated_at FROM user_contact_names WHERE owner_id = ANY($1::BIGINT[]) AND target_id = $2
`

type ListContactNamesForTargetParams struct {
	OwnerIds []int64
	TargetID int64
}

// The names several owners gave one user (how each of them sees the target).
func (q *Queries) ListContactNamesForTarget(ctx context.Context, arg ListContactNamesForTargetParams) ([]UserContactName, error) {
	rows, err := q.db.Query(ctx, listContactNamesForTarget, arg.OwnerIds, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserContactName{}
	for rows.Next() {
		var i UserContactName
		if err := rows.Scan(
			&i.OwnerID,
			&i.TargetID,
			&i.DisplayName,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrivacyExceptions = `-- name: ListPrivacyExceptions :many
SELECT owner_id, setting_key, target_user_id, effect, created_at FROM user_privacy_exceptions WHERE owner_id = $1 ORDER BY setting_key, created_at
`

func (q *Queries) ListPrivacyExceptions(ctx context.Context, ownerID int64) ([]UserPrivacyException, error) {
	rows, err := q.db.Query(ctx, listPrivacyExceptions, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserPrivacyException{}
	for rows.Next() {
		var i UserPrivacyException
		if err := rows.Scan(
			&i.OwnerID,
			&i.SettingKey,
			&i.TargetUserID,
			&i.Effect,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrivacyExceptionsForTarget = `-- name: ListPrivacyExceptionsForTarget :many
SELECT owner_id, setting_key, target_user_id, effect, created_at FROM user_privacy_exceptions WHERE owner_id = ANY($1::BIGINT[]) AND target_user_id = $2
`

type ListPrivacyExceptionsForTargetParams struct {
	OwnerIds     []int64
	TargetUserID int64
}

// The exceptions that several owners made for one user (what may that user see of each of them).
func (q *Queries) ListPrivacyExceptionsForTarget(ctx context.Context, arg ListPrivacyExceptionsForTargetParams) ([]UserPrivacyException, error) {
	rows, err := q.db.Query(ctx, listPrivacyExceptionsForTarget, arg.OwnerIds, arg.TargetUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserPrivacyException{}
	for rows.Next() {
		var i UserPrivacyException
		if err := rows.Scan(
			&i.OwnerID,
			&i.SettingKey,
			&i.TargetUserID,
			&i.Effect,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrivacyExceptionsOfOwnerFor = `-- name: ListPrivacyExceptionsOfOwnerFor :many
SELECT owner_id, setting_key, target_user_id, effect, created_at FROM user_privacy_exceptions WHERE owner_id = $1 AND target_user_id = ANY($2::BIGINT[])
`

type ListPrivacyExceptionsOfOwnerForParams struct {
	OwnerID   int64
	TargetIds []int64
}

// The exceptions one owner made for several users (what may each of them see of the owner).
func (q *Queries) ListPrivacyExceptionsOfOwnerFor(ctx context.Context, arg ListPrivacyExceptionsOfOwnerForParams) ([]UserPrivacyException, error) {
	rows, err := q.db.Query(ctx, listPrivacyExceptionsOfOwnerFor, arg.OwnerID, arg.TargetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserPrivacyException{}
	for rows.Next() {
		var i UserPrivacyException
		if err := rows.Scan(
			&i.OwnerID,
			&i.SettingKey,
			&i.TargetUserID,
			&i.Effect,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrivacySettings = `-- name: ListPrivacySettings :many

SELECT user_id, avatar_visibility, profile_visibility, presence_visibility, read_receipts_enabled, direct_messages, group_invites, search_visibility FROM user_privacy_settings WHERE user_id = ANY($1::BIGINT[])
`

// Privacy settings, exceptions, blocks and contact names: what one user lets others see and do.
func (q *Queries) ListPrivacySettings(ctx context.Context, userIds []int64) ([]UserPrivacySetting, error) {
	rows, err := q.db.Query(ctx, listPrivacySettings, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserPrivacySetting{}
	for rows.Next() {
		var i UserPrivacySetting
		if err := rows.Scan(
			&i.UserID,
			&i.AvatarVisibility,
			&i.ProfileVisibility,
			&i.PresenceVisibility,
			&i.ReadReceiptsEnabled,
			&i.DirectMessages,
			&i.GroupInvites,
			&i.SearchVisibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUsers = `-- name: SearchUsers :many
SELECT u.id, u.username, u.display_name, u.password_hash, u.avatar_url, u.bio, u.last_seen_at, u.created_at, u.updated_at, u.avatar_attachment_id
FROM users u
LEFT JOIN user_privacy_settings p ON p.user_id = u.id
WHERE (LOWER(u.username) LIKE $1::text || '%' OR LOWER(u.display_name) LIKE '%' || $2::text || '%')
  AND (u.id = $3 OR COALESCE(p.search_visibility, 'everyone') <> 'nobody')
  AND NOT EXISTS (SELECT 1 FROM user_blocks b WHERE b.blocker_id = u.id AND b.blocked_id = $3)
  AND ($4::text IS NULL OR LOWER(u.username) > $4::text)
ORDER BY LOWER(u.username)
LIMIT $5
`

type SearchUsersParams struct {
	Prefix   string
	Contains string
	ViewerID int64
	After    *string
	MaxRows  int32
}

// Users whose username starts with the query or whose display name contains it, who allow being found and
// did not block the viewer. Ordered by username, after the cursor (a lower-cased username).
func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers,
		arg.Prefix,
		arg.Contains,
		arg.ViewerID,
		arg.After,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.PasswordHash,
			&i.AvatarUrl,
			&i.Bio,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AvatarAttachmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setContactName = `-- name: SetContactName :exec
INSERT INTO user_contact_names (owner_id, target_id, display_name) VALUES ($1, $2, $3)
ON CONFLICT (owner_id, target_id) DO UPDATE SET display_name = EXCLUDED.display_name
`

type SetContactNameParams struct {
	OwnerID     int64
	TargetID    int64
	DisplayName string
}

func (q *Queries) SetContactName(ctx context.Context, arg SetContactNameParams) error {
	_, err := q.db.Exec(ctx, setContactName, arg.OwnerID, arg.TargetID, arg.DisplayName)
	return err
}

const setPrivacyException = `-- name: SetPrivacyException :exec
INSERT INTO user_privacy_exceptions (owner_id, setting_key, target_user_id, effect)
VALUES ($1, $2, $3, $4)
ON CONFLICT (owner_id, setting_key, target_user_id) DO UPDATE SET effect = EXCLUDED.effect
`

type SetPrivacyExceptionParams struct {
	OwnerID      int64
	SettingKey   string
	TargetUserID int64
	Effect       string
}

func (q *Queries) SetPrivacyException(ctx context.Context, arg SetPrivacyExceptionParams) error {
	_, err := q.db.Exec(ctx, setPrivacyException,
		arg.OwnerID,
		arg.SettingKey,
		arg.TargetUserID,
		arg.Effect,
	)
	return err
}

const sharedChatPartners = `-- name: SharedChatPartners :many
SELECT DISTINCT other.user_id
FROM participants mine
JOIN participants other ON other.chat_id = mine.chat_id
WHERE mine.user_id = $1 AND other.user_id = ANY($2::BIGINT[])
`

type SharedChatPartnersParams struct {
	ViewerID int64
	UserIds  []int64
}

// Which of the users share at least one chat with the viewer.
func (q *Queries) SharedChatPartners(ctx context.Context, arg SharedChatPartnersParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, sharedChatPartners, arg.ViewerID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var user_id int64
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unblockUser = `-- name: UnblockUser :execrows
DELETE FROM user_blocks WHERE blocker_id = $1 AND blocked_id = $2
`

type UnblockUserParams struct {
	BlockerID int64
	BlockedID int64
}

func (q *Queries) UnblockUser(ctx context.Context, arg UnblockUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, unblockUser, arg.BlockerID, arg.BlockedID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePrivacySettings = `-- name: UpdatePrivacySettings :one
INSERT INTO user_privacy_settings (
    user_id, avatar_visibility, profile_visibility, presence_visibility, read_receipts_enabled,
    direct_messages, group_invites, search_visibility
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8
)
ON CONFLICT (user_id) DO UPDATE SET
    avatar_visibility = EXCLUDED.avatar_visibility,
    profile_visibility = EXCLUDED.profile_visibility,
    presence_visibility = EXCLUDED.presence_visibility,
    read_receipts_enabled = EXCLUDED.read_receipts_enabled,
    direct_messages = EXCLUDED.direct_messages,
    group_invites = EXCLUDED.group_invites,
    search_visibility = EXCLUDED.search_visibility
RETURNING user_id, avatar_visibility, profile_visibility, presence_visibility, read_receipts_enabled, direct_messages, group_invites, search_visibility
`

type UpdatePrivacySettingsParams struct {
	UserID              int64
	AvatarVisibility    string
	ProfileVisibility   string
	PresenceVisibility  string
	ReadReceiptsEnabled bool
	DirectMessages      string
	GroupInvites        string
	SearchVisibility    string
}

func (q *Queries) UpdatePrivacySettings(ctx context.Context, arg UpdatePrivacySettingsParams) (UserPrivacySetting, error) {
	row := q.db.QueryRow(ctx, updatePrivacySettings,
		arg.UserID,
		arg.AvatarVisibility,
		arg.ProfileVisibility,
		arg.PresenceVisibility,
		arg.ReadReceiptsEnabled,
		arg.DirectMessages,
		arg.GroupInvites,
		arg.SearchVisibility,
	)
	var i UserPrivacySetting
	err := row.Scan(
		&i.UserID,
		&i.AvatarVisibility,
		&i.ProfileVisibility,
		&i.PresenceVisibility,
		&i.ReadReceiptsEnabled,
		&i.DirectMessages,
		&i.GroupInvites,
		&i.SearchVisibility,
	)
	return i, err
}
