// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcdb

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, display_name, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, display_name, password_hash, avatar_url, bio, last_seen_at, created_at, updated_at
`

type CreateUserParams struct {
	Username     string
	DisplayName  string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.DisplayName, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Bio,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensurePrivacySettings = `-- name: EnsurePrivacySettings :exec
INSERT INTO user_privacy_settings (user_id) VALUES ($1) ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) EnsurePrivacySettings(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, ensurePrivacySettings, userID)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, display_name, password_hash, avatar_url, bio, last_seen_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Bio,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, display_name, password_hash, avatar_url, bio, last_seen_at, created_at, updated_at FROM users WHERE LOWER(username) = LOWER($1)
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Bio,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockUser = `-- name: LockUser :one
SELECT id, username, display_name, password_hash, avatar_url, bio, last_seen_at, created_at, updated_at FROM users WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Bio,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockUserShared = `-- name: LockUserShared :one
SELECT id FROM users WHERE id = $1 FOR KEY SHARE
`

// Takes the lock a foreign key check would take, but up front, so operations that reference a user lock
// the user before any chat, the same order DeleteAccount uses.
func (q *Queries) LockUserShared(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockUserShared, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const rehashPassword = `-- name: RehashPassword :execrows
UPDATE users SET password_hash = $1 WHERE id = $2 AND password_hash = $3
`

type RehashPasswordParams struct {
	NewHash string
	ID      int64
	OldHash string
}

// Only replaces the hash that was verified, so a password change in between is never overwritten.
func (q *Queries) RehashPassword(ctx context.Context, arg RehashPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, rehashPassword, arg.NewHash, arg.ID, arg.OldHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPasswordHash = `-- name: SetPasswordHash :execrows
UPDATE users SET password_hash = $1 WHERE id = $2
`

type SetPasswordHashParams struct {
	PasswordHash string
	ID           int64
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPasswordHash, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchLastSeen = `-- name: TouchLastSeen :execrows
UPDATE users SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchLastSeen(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, touchLastSeen, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET display_name = $1, bio = $2, avatar_url = $3
WHERE id = $4
RETURNING id, username, display_name, password_hash, avatar_url, bio, last_seen_at, created_at, updated_at
`

type UpdateUserProfileParams struct {
	DisplayName string
	Bio         *string
	AvatarUrl   *string
	ID          int64
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Bio,
		arg.AvatarUrl,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Bio,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
