-- Schema v2, part 4: one membership model for direct chats and groups.
-- A chat is `direct` or `group`; who belongs to it is always the participants table. The owner of a group
-- is its participant with role 'owner'. There is no groups table and no user1/user2 columns.

CREATE TABLE chats (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        TEXT        NOT NULL CHECK (type IN ('direct', 'group')),
    -- Groups only. A direct chat is shown under the name of the other participant.
    name        TEXT,
    description TEXT        NOT NULL DEFAULT '',
    avatar_url  TEXT,
    -- Direct chats only: "<lower user id>:<higher user id>", so a pair of users has at most one chat.
    direct_key  TEXT,
    created_by  BIGINT REFERENCES users (id) ON DELETE SET NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT chats_shape CHECK (
        (type = 'direct' AND direct_key IS NOT NULL AND name IS NULL)
        OR (type = 'group' AND direct_key IS NULL AND char_length(btrim(name)) BETWEEN 1 AND 100)
    ),
    CONSTRAINT chats_direct_key_format CHECK (
        direct_key IS NULL
        OR (direct_key ~ '^[1-9][0-9]{0,17}:[1-9][0-9]{0,17}$'
            AND split_part(direct_key, ':', 1)::bigint < split_part(direct_key, ':', 2)::bigint)
    )
);

CREATE UNIQUE INDEX chats_direct_key_key ON chats (direct_key);
CREATE INDEX chats_created_by_idx ON chats (created_by);

CREATE TRIGGER chats_set_updated_at BEFORE UPDATE ON chats
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE participants (
    chat_id              BIGINT      NOT NULL REFERENCES chats (id) ON DELETE CASCADE,
    user_id              BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    role                 TEXT        NOT NULL DEFAULT 'member'
        CHECK (role IN ('owner', 'admin', 'moderator', 'member')),
    -- Id of the last message the user has read; messages live in ScyllaDB, so this is not a foreign key.
    last_read_message_id BIGINT CHECK (last_read_message_id >= 0),
    joined_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (chat_id, user_id)
);

-- The chats of a user.
CREATE INDEX participants_user_idx ON participants (user_id, chat_id);
-- A group has at most one owner.
CREATE UNIQUE INDEX participants_one_owner_key ON participants (chat_id) WHERE role = 'owner';

CREATE TABLE user_chat_pins (
    user_id   BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    chat_id   BIGINT      NOT NULL REFERENCES chats (id) ON DELETE CASCADE,
    pinned_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, chat_id)
);

CREATE INDEX user_chat_pins_chat_idx ON user_chat_pins (chat_id);

CREATE TABLE approval_requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type         TEXT        NOT NULL CHECK (type IN ('direct_message', 'group_invite')),
    requester_id BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    recipient_id BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status       TEXT        NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    message_text TEXT,
    chat_id      BIGINT REFERENCES chats (id) ON DELETE CASCADE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    responded_at TIMESTAMPTZ,
    CHECK (requester_id <> recipient_id),
    CHECK ((type = 'group_invite') = (chat_id IS NOT NULL))
);

-- The inbox of a recipient, pending requests first.
CREATE INDEX approval_requests_recipient_idx ON approval_requests (recipient_id, status, created_at DESC);
CREATE INDEX approval_requests_requester_idx ON approval_requests (requester_id);
CREATE INDEX approval_requests_chat_idx ON approval_requests (chat_id) WHERE chat_id IS NOT NULL;
-- No duplicate pending requests.
CREATE UNIQUE INDEX approval_requests_pending_dm_key ON approval_requests (requester_id, recipient_id)
    WHERE status = 'pending' AND type = 'direct_message';
CREATE UNIQUE INDEX approval_requests_pending_invite_key ON approval_requests (requester_id, recipient_id, chat_id)
    WHERE status = 'pending' AND type = 'group_invite';
