-- Schema v2, part 2: per-user settings and relations between users.

CREATE TABLE user_avatar_history (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    avatar_url TEXT        NOT NULL,
    is_current BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX user_avatar_history_user_idx ON user_avatar_history (user_id, created_at DESC);
-- At most one current avatar per user.
CREATE UNIQUE INDEX user_avatar_history_current_key ON user_avatar_history (user_id) WHERE is_current;

CREATE TABLE user_privacy_settings (
    user_id               BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    avatar_visibility     TEXT    NOT NULL DEFAULT 'everyone'
        CHECK (avatar_visibility IN ('everyone', 'shared_chats', 'everyone_except', 'nobody_except')),
    profile_visibility    TEXT    NOT NULL DEFAULT 'everyone'
        CHECK (profile_visibility IN ('everyone', 'shared_chats', 'everyone_except', 'nobody_except')),
    presence_visibility   TEXT    NOT NULL DEFAULT 'everyone'
        CHECK (presence_visibility IN ('everyone', 'shared_chats', 'everyone_except', 'nobody_except', 'nobody')),
    read_receipts_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    direct_messages       TEXT    NOT NULL DEFAULT 'everyone'
        CHECK (direct_messages IN ('everyone', 'shared_chats', 'wait_approval')),
    group_invites         TEXT    NOT NULL DEFAULT 'everyone'
        CHECK (group_invites IN ('everyone', 'shared_chats', 'everyone_except', 'nobody_except', 'nobody', 'wait_approval')),
    search_visibility     TEXT    NOT NULL DEFAULT 'everyone'
        CHECK (search_visibility IN ('everyone', 'nobody'))
);

CREATE TABLE user_privacy_exceptions (
    owner_id       BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    setting_key    TEXT        NOT NULL
        CHECK (setting_key IN ('avatar_visibility', 'profile_visibility', 'presence_visibility', 'group_invites')),
    target_user_id BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    effect         TEXT        NOT NULL CHECK (effect IN ('allow', 'deny')),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (owner_id, setting_key, target_user_id)
);

CREATE INDEX user_privacy_exceptions_target_idx ON user_privacy_exceptions (target_user_id);

CREATE TABLE user_blocks (
    blocker_id BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    blocked_id BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (blocker_id, blocked_id),
    CHECK (blocker_id <> blocked_id)
);

-- "Who blocked me" lookups.
CREATE INDEX user_blocks_blocked_idx ON user_blocks (blocked_id);

CREATE TABLE user_contact_names (
    owner_id     BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    target_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    display_name TEXT        NOT NULL CHECK (char_length(display_name) BETWEEN 1 AND 100),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (owner_id, target_id)
);

CREATE INDEX user_contact_names_target_idx ON user_contact_names (target_id);
