-- Schema v2, part 3: sessions, second factor, recovery and the security event log.
-- Only hashes of tokens and codes are stored.

CREATE TABLE user_security_settings (
    user_id                   BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    session_duration_days     INTEGER     NOT NULL DEFAULT 90 CHECK (session_duration_days > 0),
    two_factor_enabled        BOOLEAN     NOT NULL DEFAULT FALSE,
    two_factor_secret         TEXT,
    pending_two_factor_secret TEXT,
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER user_security_settings_set_updated_at BEFORE UPDATE ON user_security_settings
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE user_sessions (
    id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id            BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    refresh_token_hash TEXT        NOT NULL,
    user_agent         TEXT,
    ip_address         INET,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_active_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at         TIMESTAMPTZ NOT NULL,
    revoked_at         TIMESTAMPTZ
);

CREATE UNIQUE INDEX user_sessions_refresh_token_key ON user_sessions (refresh_token_hash);
-- Session list of an account.
CREATE INDEX user_sessions_user_idx ON user_sessions (user_id, last_active_at DESC) WHERE revoked_at IS NULL;
-- Cleanup of expired sessions.
CREATE INDEX user_sessions_expires_idx ON user_sessions (expires_at);

CREATE TABLE recovery_tokens (
    jti_hash   TEXT PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ
);

CREATE INDEX recovery_tokens_user_idx ON recovery_tokens (user_id);
CREATE INDEX recovery_tokens_expires_idx ON recovery_tokens (expires_at);

CREATE TABLE two_factor_challenges (
    jti_hash   TEXT PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ NOT NULL,
    attempts   INTEGER     NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    used_at    TIMESTAMPTZ
);

CREATE INDEX two_factor_challenges_user_idx ON two_factor_challenges (user_id);
CREATE INDEX two_factor_challenges_expires_idx ON two_factor_challenges (expires_at);

CREATE TABLE user_2fa_recovery_codes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    code_hash  TEXT        NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    used_at    TIMESTAMPTZ
);

-- Unused codes of an account.
CREATE INDEX user_2fa_recovery_codes_user_idx ON user_2fa_recovery_codes (user_id) WHERE used_at IS NULL;

-- Append-only log of security-relevant events (login, password change, 2FA, session revocation, ...).
CREATE TABLE user_security_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    event_type TEXT        NOT NULL CHECK (char_length(event_type) BETWEEN 1 AND 64),
    ip_address INET,
    user_agent TEXT,
    -- Never put secrets, tokens or message content here.
    details    JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX user_security_events_user_idx ON user_security_events (user_id, created_at DESC, id DESC);
