-- Schema v2, part 1: accounts.
-- Messages live in ScyllaDB (migrations/scylla); this schema covers everything else.
-- Conventions: BIGINT identity keys, TIMESTAMPTZ with a now() default, an explicit ON DELETE rule on
-- every foreign key, and an index on every referencing column (cascades need them).

CREATE FUNCTION set_updated_at() RETURNS trigger
    LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT        NOT NULL,
    display_name  TEXT        NOT NULL,
    password_hash TEXT        NOT NULL,
    avatar_url    TEXT,
    bio           TEXT,
    last_seen_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- Same rule as the registration form (MSGC-41); older accounts may still have capital letters.
    CONSTRAINT users_username_format CHECK (username ~ '^[A-Za-z0-9_]{3,32}$'),
    CONSTRAINT users_display_name_length CHECK (char_length(btrim(display_name)) BETWEEN 1 AND 100)
);

-- Usernames are unique regardless of case.
CREATE UNIQUE INDEX users_username_lower_key ON users (LOWER(username));

CREATE TRIGGER users_set_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- TEMPORARY: the key-splitting data of the v1 recovery flow, kept only until the port of MSGC-69 no
-- longer needs it. It is a separate table so that dropping it later leaves `users` untouched.
CREATE TABLE user_recovery_shares (
    user_id                 BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    encrypted_cloud_part    TEXT,
    salt                    BYTEA,
    verification_ciphertext TEXT
);
