-- The schema of the Python backend (server/database.py, setup_database), for the migration test.

CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT UNIQUE NOT NULL,
                display_name TEXT NOT NULL,
                password TEXT NOT NULL,
                avatar_url TEXT,
                bio TEXT,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                last_seen TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                encrypted_cloud_part TEXT,
                salt BYTEA,
                verification_ciphertext TEXT
            );

CREATE TABLE IF NOT EXISTS chats (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT NOT NULL,
                type TEXT NOT NULL DEFAULT 'one-on-one',
                description TEXT DEFAULT '',
                avatar_url TEXT,
                user1_id BIGINT REFERENCES users(id),
                user2_id BIGINT REFERENCES users(id)
            );

CREATE TABLE IF NOT EXISTS user_avatar_history (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id),
                avatar_url TEXT NOT NULL,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                is_current BOOLEAN NOT NULL DEFAULT FALSE
            );

CREATE TABLE IF NOT EXISTS user_privacy_settings (
                user_id BIGINT PRIMARY KEY REFERENCES users(id),
                avatar_visibility TEXT NOT NULL DEFAULT 'everyone',
                profile_visibility TEXT NOT NULL DEFAULT 'everyone',
                presence_visibility TEXT NOT NULL DEFAULT 'everyone',
                read_receipts_enabled BOOLEAN NOT NULL DEFAULT TRUE,
                direct_messages TEXT NOT NULL DEFAULT 'everyone',
                group_invites TEXT NOT NULL DEFAULT 'everyone',
                search_visibility TEXT NOT NULL DEFAULT 'everyone'
            );

CREATE TABLE IF NOT EXISTS user_privacy_exceptions (
                owner_id BIGINT NOT NULL REFERENCES users(id),
                setting_key TEXT NOT NULL,
                target_user_id BIGINT NOT NULL REFERENCES users(id),
                effect TEXT NOT NULL,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (owner_id, setting_key, target_user_id)
            );

CREATE TABLE IF NOT EXISTS approval_requests (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                type TEXT NOT NULL,
                requester_id BIGINT NOT NULL REFERENCES users(id),
                recipient_id BIGINT NOT NULL REFERENCES users(id),
                status TEXT NOT NULL DEFAULT 'pending',
                message_text TEXT,
                chat_id BIGINT REFERENCES chats(id),
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                responded_at TIMESTAMPTZ
            );

CREATE TABLE IF NOT EXISTS user_security_settings (
                user_id BIGINT PRIMARY KEY REFERENCES users(id),
                session_duration_days INTEGER NOT NULL DEFAULT 90,
                two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
                two_factor_secret TEXT,
                pending_two_factor_secret TEXT,
                updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
            );

CREATE TABLE IF NOT EXISTS user_sessions (
                id TEXT PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id),
                refresh_token_hash TEXT NOT NULL,
                user_agent TEXT,
                ip_address TEXT,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                last_active_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                expires_at TIMESTAMPTZ NOT NULL,
                revoked_at TIMESTAMPTZ
            );

CREATE TABLE IF NOT EXISTS recovery_tokens (
                jti_hash TEXT PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                expires_at TIMESTAMPTZ NOT NULL,
                used_at TIMESTAMPTZ
            );

CREATE TABLE IF NOT EXISTS two_factor_challenges (
                jti_hash TEXT PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                expires_at TIMESTAMPTZ NOT NULL,
                attempts INTEGER NOT NULL DEFAULT 0,
                used_at TIMESTAMPTZ
            );

CREATE TABLE IF NOT EXISTS user_2fa_recovery_codes (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users(id),
                code_hash TEXT NOT NULL,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                used_at TIMESTAMPTZ
            );

CREATE TABLE IF NOT EXISTS user_blocks (
                blocker_id BIGINT NOT NULL REFERENCES users(id),
                blocked_id BIGINT NOT NULL REFERENCES users(id),
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (blocker_id, blocked_id)
            );

CREATE TABLE IF NOT EXISTS user_contact_names (
                owner_id BIGINT NOT NULL REFERENCES users(id),
                target_id BIGINT NOT NULL REFERENCES users(id),
                display_name TEXT NOT NULL,
                updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (owner_id, target_id)
            );

CREATE TABLE IF NOT EXISTS user_chat_pins (
                user_id BIGINT NOT NULL REFERENCES users(id),
                chat_id BIGINT NOT NULL REFERENCES chats(id),
                pinned_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (user_id, chat_id)
            );

CREATE TABLE IF NOT EXISTS groups (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                chat_id BIGINT NOT NULL REFERENCES chats(id),
                admin_id BIGINT NOT NULL REFERENCES users(id)
            );

CREATE TABLE IF NOT EXISTS participants (
                chat_id BIGINT NOT NULL REFERENCES chats(id),
                user_id BIGINT NOT NULL REFERENCES users(id),
                role TEXT NOT NULL DEFAULT 'member',
                PRIMARY KEY (chat_id, user_id)
            );

CREATE TABLE IF NOT EXISTS messages (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                chat_id BIGINT NOT NULL REFERENCES chats(id),
                sender_id BIGINT NOT NULL,
                sender_name TEXT NOT NULL,
                content TEXT NOT NULL,
                timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                edited_at TIMESTAMPTZ,
                reply_to BIGINT REFERENCES messages(id),
                reactions TEXT DEFAULT '[]',
                read_by TEXT DEFAULT '[]',
                delivery_error TEXT,
                undelivered_to TEXT DEFAULT '[]',
                audio_duration DOUBLE PRECISION,
                audio_waveform TEXT,
                forwarded_from_message_id BIGINT,
                forwarded_from_sender_id BIGINT,
                forwarded_from_sender_name TEXT,
                forwarded_from_sender_username TEXT,
                deleted_for TEXT DEFAULT '[]'
            );

CREATE TABLE IF NOT EXISTS message_attachments (
                message_id BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
                file_path TEXT NOT NULL,
                PRIMARY KEY (message_id, file_path)
            );

